authors:
- Gaurav Rastogi <grastogi@vmware.com>
- Sandeep Bandi <sabandi@vmware.com>
- Amol Shinde <samol@vmware.com>
description: VMware Advanced Load Balancer (formerly Avi) Ansible Collection
issues: https://github.com/vmware/ansible-collection-alb/issues
license_file: LICENSE
name: alb
namespace: vmware
readme: README.md
repository: https://github.com/vmware/ansible-collection-alb
tags:
- avi
- controller
- avicontroller
- avisdk
- avinetworks
- network
- load
- balancer
- sdk
version: 22.1.1
