galaxy_info:
  role_name: avise_vmware
  author: Avi Networks
  description: Ansible Role to setup Avi Service Engine on VMware
  company: Avi Networks
  license: Apache-2.0
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
    - xenial
  galaxy_tags:
    - avi
    - service
    - engine
    - avise
    - avisdk
    - avinetworks
    - networks
    - load
    - balancer
    - sdk
    - lbaas
    - lb
    - virtualserver
    - cloud
    - loadbalancer
    - gslb
    - vmware
    - vcenter
dependencies:
  - { role: avinetworks.avisdk }
